const String CONTENT_TEXT_COLOR = 'CONTENT_TEXT_COLOR';
const String CONTENT_BACKGROUND_COLOR = 'CONTENT_BACKGROUND_COLOR';
const String CONTENT_FONT_SIZE = 'CONTENT_FONT_SIZE';
const String CONTENT_FONT_FAMILY = 'CONTENT_FONT_FAMILY';

const int ITEMS_IN_ROW = 30;
